// minecraftforge 1.12.2 mod dev

buildscript {
    repositories {
        maven {
            name 'Maven Central'
            url 'https://repo.maven.apache.org/maven2/'
        }
        maven {
            name 'Forge'
            url 'https://maven.minecraftforge.net/releases/'
        }
        maven {
            name 'NeoForged'
            url 'https://maven.neoforged.net/releases/'
        }
        maven {
            name 'Sonatype'
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

plugins {
    id 'com.palantir.git-version' version '0.13.0' apply false
}

apply plugin: 'net.minecraftforge.gradle.forge'

if (project.file('.git/HEAD').isFile()) {
    apply plugin: 'com.palantir.git-version'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

eclipse {
    project {
        buildCommands = []
    }
}

tasks.eclipse.dependsOn setupDecompWorkspace
tasks.idea.dependsOn setupDecompWorkspace

if (JavaVersion.current() != JavaVersion.VERSION_1_8) {
    throw new GradleException("This project requires Java 8, but it's running on " + JavaVersion.current())
}

checkPropertyExists("mod_name")
checkPropertyExists("mod_id")
checkPropertyExists("mod_group")
checkPropertyExists("minecraft_version")
checkPropertyExists("forge_version")
checkPropertyExists("mcp_mappings")
checkPropertyExists("replace_gradle_token_in_file")
checkPropertyExists("gradle_token_mod_id")
checkPropertyExists("gradle_token_mod_name")
checkPropertyExists("gradle_token_version")
checkPropertyExists("gradle_token_group_name")
checkPropertyExists("development_environment_username")

propertyDefaultIfUnset("api_package", "")

def mod_group_path = mod_group.toString().replaceAll("\\.", "/")
def api_package_path = api_package.toString().replaceAll("\\.", "/")

String identified_version
String version_override = System.getenv("VERSION") ?: null
boolean explicit_version
if (version_override != null) {
    identified_version = version_override
    explicit_version = true
} else try {
    identified_version = gitVersion()
    def details = versionDetails()
    explicit_version = details.isCleanTag
} catch (Exception ignored) {
    println('This mod must be version controlled by Git AND the repository must provide at least one tag,\n' +
            'or the VERSION override must be set!')
    version_override = 'NO-GIT-TAG-SET'
    identified_version = version_override
    explicit_version = false
}
version = minecraft_version + '-' + identified_version
ext {
    mod_version = identified_version
}

if (identified_version == version_override) {
    println("Override version to ${mod_version}")
}

group = mod_group
archivesBaseName = mod_id

def arguments = []
def jvmArguments = []

minecraft {
    version = minecraft_version + "-" + forge_version
    runDir = "run"
    mappings = mcp_mappings

    if (replace_gradle_token_in_file) {
        for (f in replace_gradle_token_in_file.split(',')) {
            replaceIn f
        }
        if (gradle_token_mod_id) {
            replace gradle_token_mod_id, mod_id
        }
        if (gradle_token_mod_name) {
            replace gradle_token_mod_name, mod_name
        }
        if (gradle_token_version) {
            replace gradle_token_version, mod_version
        }
        if (gradle_token_group_name) {
            replace gradle_token_group_name, mod_group
        }
    }
}

apply from: 'dependencies.gradle'

sourceSets {
    devmode {
        compileClasspath += sourceSets.main.compileClasspath
        compileClasspath += sourceSets.main.output
        java { setSrcDirs(['src/dev/java']) }
        resources { setSrcDirs(['src/dev/resources']) }
    }
}

sourceSets.devmode.resources.matching {
    include 'META-INF/*_at.cfg'
}.each { at->
    minecraft.atSource at
}

runClient {
    if (development_environment_username) {
        arguments += [
            "--username",
            development_environment_username
        ]
    }

    args(arguments)
    jvmArgs(jvmArguments)
}

runServer {
    args(arguments)
    jvmArgs(jvmArguments)
}

task runClientDev {
    dependsOn 'devmodeJar'
    doFirst {
        tasks.named('runClient').configure {
            dependsOn -= tasks.jar
            classpath = classpath.filter { it != tasks.jar.archivePath }
            classpath file(tasks.devmodeJar.archivePath)
        }
    }
    finalizedBy 'runClient'
}

task runServerDev {
    dependsOn 'devmodeJar'
    doFirst {
        tasks.named('runServer').configure {
            dependsOn -= tasks.jar
            classpath = classpath.filter { it != tasks.jar.archivePath }
            classpath file(tasks.devmodeJar.archivePath)
        }
    }
    finalizedBy 'runServer'
}

jar {
    manifest {
        attributes(getManifestAttributes())
    }
}

jar.finalizedBy('reobfJar')

task determinizeJar(type: Zip) {
    dependsOn reobfJar
    def jarPath = reobfJar.jar
    from zipTree(jarPath)
    archiveName = jarPath.name
    destinationDir = temporaryDir
    doLast {
        copy {
            from archivePath
            into jarPath.parent
        }
        archivePath.delete()
    }
}

tasks.withType(AbstractArchiveTask) {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

reobfJar.finalizedBy('determinizeJar')

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand "version":project.version,
               "minecraftVersion": project.minecraft.version,
               "modVersion": mod_version,
               "modId": mod_id,
               "modName": mod_name
    }

    from(sourceSets.main.resources.srcDirs) {
        include 'assets/' + mod_id + '/lang/*.json'

        eachFile { fileInfo ->
            def outDir = fileInfo.relativePath.parent.getFile(destinationDir)
            convertJsonLangFile(file, outDir)
        }
    }

    if (explicit_version) {
        from(sourceSets.main.resources.srcDirs) {
            include 'assets/' + mod_id + '/protocol_versions.json'

            eachFile { fileInfo->
                def versionsMap = new groovy.json.JsonSlurper().parse(file)
                if (!versionsMap.containsKey(mod_version)) {
                    throw new GradleException("Can't find \"${mod_version}\" in ${fileInfo.name} file")
                }
            }
        }
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'assets/' + mod_id + '/lang/*.json'
        exclude 'mcmod.info'
        exclude 'pack.mcmeta'
        exclude 'pack.png'
    }

    doLast {
        fileTree(dir: destinationDir, include: 'assets/' + mod_id + '/lang/*.json').each { file ->
            file.delete()
        }
    }
}

task combineDevmodeResourceSources(type: Copy) {
    destinationDir = new File(project.buildDir, "combinedResources/devmode")
    doFirst {
        delete destinationDir
    }
    from(sourceSets.devmode.resources.srcDirs) {
        include 'assets/' + mod_id + '/lang/*.json'

        eachFile { fileInfo ->
            def outDir = fileInfo.relativePath.parent.getFile(destinationDir)
            def mainFile = sourceSets.main.resources.find{file->file.path.endsWith(fileInfo.sourcePath)}
            if (mainFile != null) {
                def outJsonFile = new File(destinationDir, fileInfo.path)
                outJsonFile.getParentFile().mkdirs()
                combineJsonLangFiles(mainFile, file, outJsonFile)
                fileInfo.exclude()
            }
        }
    }
    from(sourceSets.devmode.resources.srcDirs) {
        include 'META-INF/*_at.cfg'

        eachFile { fileInfo ->
            def mainFile = sourceSets.main.resources.find{file->file.path.endsWith(fileInfo.sourcePath)}
            if (mainFile != null) {
                def outJsonFile = new File(destinationDir, fileInfo.path)
                outJsonFile.getParentFile().mkdirs()
                outJsonFile.text = mainFile.text + '\n' + file.text
                fileInfo.exclude()
            }
        }
    }
    from(sourceSets.main.resources.srcDirs) {
        include 'assets/' + mod_id + '/lang/*.json'
        include 'META-INF/*_at.cfg'
        eachFile { fileInfo -> fileInfo.exclude() }
    }
}

processDevmodeResources {
    dependsOn 'processResources'
    dependsOn 'combineDevmodeResourceSources'

    from(tasks.combineDevmodeResourceSources.destinationDir) {
        include 'assets/' + mod_id + '/lang/*.json'

        eachFile { fileInfo ->
            def outDir = fileInfo.relativePath.parent.getFile(destinationDir)
            convertJsonLangFile(file, outDir)
        }
    }

    from(tasks.combineDevmodeResourceSources.destinationDir) {
        include 'META-INF/*_at.cfg'
    }

    doLast {
        fileTree(dir: destinationDir, include: 'assets/' + mod_id + '/lang/*.json').each { file ->
            file.delete()
        }
    }
}

def getManifestAttributes() {
    def manifestAttributes = [:]
    manifestAttributes += ["FMLAT": "${mod_id}_at.cfg"]
    return manifestAttributes
}

sourceJar {
    enabled = false
    dependsOn.clear()
}

task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
    dependsOn 'processResources'
    from(sourceSets.main.output) {
        include 'assets/' + mod_id + '/lang/*.lang'
    }
    from file("$projectDir/LICENSE")
}

task deobfJar(type: Jar) {
    classifier = 'deobf'
    dependsOn 'processResources'
    from sourceSets.main.output
    manifest {
        attributes(getManifestAttributes())
    }
}

task apiJar(type: Jar) {
    classifier = 'api'
    from(sourceSets.main.allSource) {
        include mod_group_path + "/" + api_package_path + '/**'
    }
    from(sourceSets.main.output) {
        include mod_group_path + "/" + api_package_path + '/**'
    }
    from file("$projectDir/LICENSE")
}

task devmodeDeobfJar(type: Jar) {
    classifier = 'devmode-deobf'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {}
    dependsOn 'processResources'
    from(sourceSets.main.output) {}
    manifest {
        attributes(getManifestAttributes())
    }
}

task devmodeJar(type: Jar) {
    classifier = 'devmode'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {}
    dependsOn 'processResources'
    from(sourceSets.main.output) {}
    manifest {
        attributes(getManifestAttributes())
    }
    finalizedBy 'reobfDevmodeJar'
}

reobf.create('devmodeJar')
reobfDevmodeJar {
    finalizedBy 'determinizeDevmodeJar'
}

task determinizeDevmodeJar(type: Zip) {
    dependsOn reobfDevmodeJar
    def jarPath = reobfDevmodeJar.jar
    from zipTree(jarPath)
    archiveName = jarPath.name
    destinationDir = temporaryDir
    doLast {
        copy {
            from archivePath
            into jarPath.parent
        }
        archivePath.delete()
    }
}

task devmodeSourcesJar(type: Jar) {
    classifier = 'devmode-sources'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'combineDevmodeResourceSources'
    from(tasks.combineDevmodeResourceSources.destinationDir) {}
    from(sourceSets.devmode.allSource) {}
    from(sourceSets.main.allSource) {}
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {
        include 'assets/' + mod_id + '/lang/*.lang'
    }
    dependsOn 'processResources'
    from(sourceSets.main.output) {
        include 'assets/' + mod_id + '/lang/*.lang'
    }
    from file("$projectDir/LICENSE")
}

artifacts {
    archives sourcesJar
    archives deobfJar
    if (api_package) {
        archives apiJar
    }
    archives devmodeJar
    archives devmodeDeobfJar
    archives devmodeSourcesJar
}

// Helper methods

def convertJsonLangFile(File jsonFile, File outDir) {
    def matcher = jsonFile.name =~ /^([a-zA-Z0-9]+)_([a-zA-Z0-9]+).json$/
    matcher.find()
    def language = matcher.group(1)
    def region = matcher.group(2)
    def fileName = language + '_' + region.toUpperCase() + '.lang'
    def langFile = new File(outDir, fileName)
    def translation = new groovy.json.JsonSlurper().parse(jsonFile)
    langFile.withWriter { wr ->
        translation.each { e ->
            wr.println e.key + '=' + e.value
        }
    }
}

def combineJsonLangFiles(File firstFile, File secondFile, File outFile) {
    outFile.text = (
        firstFile.text.replaceAll('\\s*}$', ',') +
        secondFile.text.replaceAll('^\\{', '')
    ).replaceAll(',(\\s*)}$', '$1}')
}

def checkPropertyExists(String propertyName) {
    if (!project.hasProperty(propertyName)) {
        throw new GradleException("This project requires a property \"" +
                                  propertyName + "\"! Please add it your \"gradle.properties\".")
    }
}

def propertyDefaultIfUnset(String propertyName, defaultValue) {
    if (!project.hasProperty(propertyName) || project.property(propertyName) == "") {
        project.ext.setProperty(propertyName, defaultValue)
    }
}
