// minecraftforge mod dev

buildscript {
    repositories {
        maven {
            name 'Maven Central'
            url 'https://repo.maven.apache.org/maven2/'
        }
        maven {
            name 'Forge'
            url 'https://maven.minecraftforge.net/releases/'
        }
        maven {
            name 'NeoForged'
            url 'https://maven.neoforged.net/releases/'
        }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '[6.0,6.2)', changing: true
    }
}

plugins {
    id 'com.palantir.git-version' version '0.13.0' apply false
    id 'org.parchmentmc.librarian.forgegradle' version '1.+' apply false
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: 'eclipse'

if (project.file('.git/HEAD').isFile()) {
    apply plugin: 'com.palantir.git-version'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

checkPropertyExists("mod_name")
checkPropertyExists("mod_id")
checkPropertyExists("mod_group")
checkPropertyExists("minecraft_version")
checkPropertyExists("minecraft_version_range")
checkPropertyExists("forge_version")
checkPropertyExists("forge_version_range")
checkPropertyExists("development_environment_username")

propertyDefaultIfUnset("api_package", "")

propertyDefaultIfUnset("mcp_mappings_channel", "official")
propertyDefaultIfUnset("mcp_mappings_version", "${minecraft_version}")

def mod_group_path = mod_group.toString().replaceAll("\\.", "/")
def api_package_path = api_package.toString().replaceAll("\\.", "/")

String identified_version
String version_override = System.getenv("VERSION") ?: null
try {
    identified_version = (version_override == null) ? gitVersion() : version_override
} catch (Exception ignored) {
    println('This mod must be version controlled by Git AND the repository must provide at least one tag,\n' +
            'or the VERSION override must be set!')
    version_override = 'NO-GIT-TAG-SET'
    identified_version = version_override
}
version = minecraft_version + '-' + identified_version
ext {
    mod_version = identified_version
}

if (identified_version == version_override) {
    println("Override version to ${mod_version}")
}

group = mod_group
archivesBaseName = mod_id

minecraft {
    mappings channel: "${mcp_mappings_channel}", version: "${mcp_mappings_version}"

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file('run')

            if (development_environment_username) {
                arg "--username=${development_environment_username}"
            }
        }
        server {
            workingDirectory project.file('run')
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

apply from: 'dependencies.gradle'

sourceSets {
    devmode {
        compileClasspath += sourceSets.main.compileClasspath
        compileClasspath += sourceSets.main.output
        java { setSrcDirs(['src/dev/java']) }
        resources { setSrcDirs(['src/dev/resources']) }
    }
    devmodeCombined {
        compileClasspath = sourceSets.main.compileClasspath
        runtimeClasspath = sourceSets.main.runtimeClasspath
        java { setSrcDirs([]) }
        resources { setSrcDirs([]) }
    }
}

sourceSets.devmode.resources.matching {
    include 'META-INF/accesstransformer.cfg'
}.each { at->
    minecraft.accessTransformers at
}

task runClientDev {
    dependsOn 'devmodeCombinedClasses'
    doFirst {
        minecraft.runs.client {
            setSources([sourceSets.devmodeCombined])
        }
    }
    finalizedBy 'runClient'
}

task runServerDev {
    dependsOn 'devmodeCombinedClasses'
    doFirst {
        minecraft.runs.client {
            setSources([sourceSets.devmodeCombined])
        }
    }
    finalizedBy 'runServer'
}

jar.finalizedBy('reobfJar')

tasks.withType(AbstractArchiveTask) {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

processResources {
    doFirst {
        delete(
            files("${buildDir}/resources/main/META-INF/mods.toml",
                  "${buildDir}/resources/main/pack.mcmeta")
        )
    }

    exclude '.cache'

    filesMatching("META-INF/mods.toml") {
        expand 'mod_version': mod_version,
               'mod_name':    mod_name,
               'mod_id':      mod_id,
               'minecraft_version_range': minecraft_version_range,
               'forge_version_range':     forge_version_range
    }
    filesMatching("pack.mcmeta") {
        expand 'mod_id': mod_id
    }
}

processDevmodeResources {
    dependsOn 'processResources'

    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.devmode.resources.srcDirs) {
        include 'assets/' + mod_id + '/lang/*.json'

        eachFile { fileInfo ->
            def outDir = fileInfo.relativePath.parent.getFile(destinationDir)
            def mainFile = sourceSets.main.resources.find{file->file.path.endsWith(fileInfo.sourcePath)}
            if (mainFile != null) {
                def outJsonFile = new File(destinationDir, fileInfo.path)
                outJsonFile.getParentFile().mkdirs()
                combineJsonLangFiles(mainFile, file, outJsonFile)
                fileInfo.exclude()
            }
        }
    }
    from(sourceSets.devmode.resources.srcDirs) {
        include 'META-INF/accesstransformer.cfg'

        eachFile { fileInfo ->
            def mainFile = sourceSets.main.resources.find{file->file.path.endsWith(fileInfo.sourcePath)}
            if (mainFile != null) {
                def outJsonFile = new File(destinationDir, fileInfo.path)
                outJsonFile.getParentFile().mkdirs()
                outJsonFile.text = mainFile.text + '\n' + file.text
                fileInfo.exclude()
            }
        }
    }
}

tasks.devmodeCombinedClasses.finalizedBy 'devmodeCombinedClassesCopy'
task devmodeCombinedClassesCopy(type: Copy) {
    destinationDir = sourceSets.devmodeCombined.output.classesDirs.singleFile
    doFirst {
        delete destinationDir
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'devmodeClasses'
    from(sourceSets.devmode.output.classesDirs) {}
    dependsOn 'classes'
    from(sourceSets.main.output.classesDirs) {}
}

processDevmodeCombinedResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output.resourcesDir) {}
    dependsOn 'processResources'
    from(sourceSets.main.output.resourcesDir) {}
}

task sourcesJar(type: Jar) {
    archiveClassifier = 'sources'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processResources'
    from(sourceSets.main.output) {
        include 'META-INF/mods.toml'
    }
    from(sourceSets.main.allSource) {}
    from file("$projectDir/LICENSE")
}

task deobfJar(type: Jar) {
    archiveClassifier = 'deobf'
    dependsOn 'processResources'
    from sourceSets.main.output
}

task apiJar(type: Jar) {
    archiveClassifier = 'api'
    from(sourceSets.main.allSource) {
        include mod_group_path + "/" + api_package_path + '/**'
    }
    from(sourceSets.main.output) {
        include mod_group_path + "/" + api_package_path + '/**'
    }
    from file("$projectDir/LICENSE")
}

task devmodeDeobfJar(type: Jar) {
    archiveClassifier = 'devmode-deobf'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {}
    dependsOn 'processResources'
    from(sourceSets.main.output) {}
}

task devmodeJar(type: Jar) {
    archiveClassifier = 'devmode'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {}
    dependsOn 'processResources'
    from(sourceSets.main.output) {}
    finalizedBy 'reobfDevmodeJar'
}

reobf.create('devmodeJar')

task devmodeSourcesJar(type: Jar) {
    archiveClassifier = 'devmode-sources'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {
        include 'assets/' + mod_id + '/lang/*.json'
        include 'META-INF/accesstransformer.cfg'
    }
    dependsOn 'processResources'
    from(sourceSets.main.output) {
        include 'META-INF/mods.toml'
    }
    from(sourceSets.devmode.allSource) {}
    from(sourceSets.main.allSource) {}
    from file("$projectDir/LICENSE")
}

artifacts {
    archives sourcesJar
    archives deobfJar
    if (api_package) {
        archives apiJar
    }
    archives devmodeJar
    archives devmodeDeobfJar
    archives devmodeSourcesJar
}

// Helper methods

def combineJsonLangFiles(File firstFile, File secondFile, File outFile) {
    outFile.text = (
        firstFile.text.replaceAll('\\s*}$', ',') +
        secondFile.text.replaceAll('^\\{', '')
    ).replaceAll(',(\\s*)}$', '$1}')
}

def checkPropertyExists(String propertyName) {
    if (!project.hasProperty(propertyName)) {
        throw new GradleException("This project requires a property \"" +
                                  propertyName + "\"! Please add it your \"gradle.properties\".")
    }
}

def propertyDefaultIfUnset(String propertyName, defaultValue) {
    if (!project.hasProperty(propertyName) || project.property(propertyName) == "") {
        project.ext.setProperty(propertyName, defaultValue)
    }
}
