// Based on https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/408c4febad24bc65cade069f719f358d657aab51/build.gradle

import org.gradle.internal.logging.text.StyledTextOutput.Style
import org.gradle.internal.logging.text.StyledTextOutputFactory

import java.util.concurrent.TimeUnit
import java.util.stream.Collectors

import net.minecraftforge.gradle.delayed.*
import net.minecraftforge.gradle.tasks.user.reobf.*

buildscript {
    repositories {
        maven {
            name 'Maven Central'
            url 'https://repo.maven.apache.org/maven2/'
        }
        maven {
            name 'Forge'
            url 'https://maven.minecraftforge.net/releases/'
        }
        maven {
            name 'NeoForged'
            url 'https://maven.neoforged.net/releases/'
        }
        maven {
            // GTNH ForgeGradle and ASM Fork
            name 'GTNH Maven'
            url 'https://nexus.gtnewhorizons.com/repository/public/'
        }
        maven {
            name 'Sonatype'
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
        maven {
            name 'Scala CI dependencies'
            url 'https://repo1.maven.org/maven2/'
        }
    }
    dependencies {
        classpath 'org.ow2.asm:asm-debug-all-custom:5.0.3'
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.2.13'
    }
    configurations.all {
        resolutionStrategy {
            // Forcing versions for outdated packages
            force 'org.eclipse.jdt:org.eclipse.jdt.core:3.10.0'
        }
    }
}
plugins {
    id 'java-library'
    id 'idea'
    id 'eclipse'
    id 'org.jetbrains.kotlin.jvm' version '1.5.30' apply false
    id 'org.jetbrains.kotlin.kapt' version '1.5.30' apply false
    id 'com.google.devtools.ksp' version '1.5.30-1.0.0' apply false
    id 'org.ajoberstar.grgit' version '4.1.1'
    id 'com.github.johnrengelman.shadow' version '4.0.4'
    id 'com.palantir.git-version' version '0.13.0' apply false
    id 'de.undercouch.download' version '5.0.1'
    id 'com.github.gmazzo.buildconfig' version '3.0.3' apply false
}

repositories {
    maven {
        name 'Overmind forge repo mirror'
        url 'https://gregtech.overminddl1.com/'
    }
}

dependencies {
    implementation 'com.diffplug:blowdryer:1.6.0'
}

apply plugin: 'com.diffplug.blowdryer'

if (project.file('.git/HEAD').isFile()) {
    apply plugin: 'com.palantir.git-version'
}

apply plugin: 'forge'

def out = services.get(StyledTextOutputFactory).create('an-output')
def projectJavaVersion = JavaLanguageVersion.of(8)

java {
    toolchain {
        languageVersion.set(projectJavaVersion)
    }
}

idea {
    module {
        inheritOutputDirs = true
        downloadJavadoc = true
        downloadSources = true
    }
}

eclipse {
    project {
        buildCommands = []
    }
}

tasks.eclipse.dependsOn setupDecompWorkspace
tasks.idea.dependsOn setupDecompWorkspace

if (JavaVersion.current() != JavaVersion.VERSION_1_8) {
    throw new GradleException("This project requires Java 8, but it's running on " + JavaVersion.current())
}

checkPropertyExists("modName")
checkPropertyExists("modId")
checkPropertyExists("modGroup")

checkPropertyExists("minecraftVersion")
checkPropertyExists("forgeVersion")
checkPropertyExists("codechickenlibVersion")
checkPropertyExists("codechickencoreVersion")
checkPropertyExists("notenoughitemsVersion")
checkPropertyExists("computercraftVersion")

checkPropertyExists("developmentEnvironmentUserName")

checkPropertyExists("replaceGradleTokenInFile")
checkPropertyExists("gradleTokenModId")
checkPropertyExists("gradleTokenModName")
checkPropertyExists("gradleTokenVersion")
checkPropertyExists("gradleTokenGroupName")

propertyDefaultIfUnset("apiPackage", "")
propertyDefaultIfUnset("accessTransformersFile", "")
propertyDefaultIfUnset("coreModClass", "")

propertyDefaultIfUnset("channel", "stable")
propertyDefaultIfUnset("mappingsVersion", "12")

final String javaSourceDir = "src/main/java/"
final String scalaSourceDir = "src/main/scala/"
final String kotlinSourceDir = "src/main/kotlin/"

final String modGroupPath = modGroup.toString().replaceAll("\\.", "/")
final String apiPackagePath = apiPackage.toString().replaceAll("\\.", "/")

final String targetPackageJava = javaSourceDir + modGroupPath
final String targetPackageScala = scalaSourceDir + modGroupPath
final String targetPackageKotlin = kotlinSourceDir + modGroupPath
final def targetPackages = [targetPackageJava, targetPackageScala, targetPackageKotlin]
if (!targetPackages.stream().anyMatch{getFile(it).exists()}) {
    throw new GradleException("Could not resolve \"modGroup\"! Could not find " + targetPackages.join(" or "))
}

if (apiPackage) {
    def targetPackagesApi = targetPackages.stream().map{it + "/" + apiPackagePath}.collect(Collectors.toList())
    if (!targetPackagesApi.stream().anyMatch{getFile(it).exists()}) {
        throw new GradleException("Could not resolve \"apiPackage\"! Could not find " + targetPackagesApi.join(" or "))
    }
}

if (accessTransformersFile) {
    String targetFile = "src/main/resources/META-INF/" + accessTransformersFile
    if (!getFile(targetFile).exists()) {
        throw new GradleException("Could not resolve \"accessTransformersFile\"! Could not find " + targetFile)
    }
}

if (coreModClass) {
    final String coreModPath = coreModClass.toString().replaceAll("\\.", "/")
    String targetFileJava = targetPackageJava + "/" + coreModPath + ".java"
    String targetFileScala = targetPackageScala + "/" + coreModPath + ".scala"
    String targetFileScalaJava = targetPackageScala + "/" + coreModPath + ".java"
    String targetFileKotlin = targetPackageKotlin + "/" + coreModPath + ".kt"
    def targetFiles = [targetFileJava, targetFileScala, targetFileScalaJava, targetFileKotlin]
    if (!targetFiles.stream().anyMatch{getFile(it).exists()}) {
        throw new GradleException("Could not resolve \"coreModClass\"! Could not find " + targetFiles.join(" or "))
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, TimeUnit.SECONDS)
    System.setProperty("org.gradle.internal.http.connectionTimeout", 120000 as String)
    System.setProperty("org.gradle.internal.http.socketTimeout", 120000 as String)
}

String identifiedVersion
String versionOverride = System.getenv("VERSION") ?: null
boolean explicitVersion
if (versionOverride != null) {
    identifiedVersion = versionOverride
    explicitVersion = true
} else try {
    identifiedVersion = gitVersion()
    def details = versionDetails()
    explicitVersion = details.isCleanTag
} catch (Exception ignored) {
    out.style(Style.Failure).text(
        'This mod must be version controlled by Git AND the repository must provide at least one tag,\n' +
            'or the VERSION override must be set! ').style(Style.SuccessHeader).text('(Do NOT download from GitHub using the ZIP option, instead\n' +
        'clone the repository, see ').style(Style.Info).text('https://gtnh.miraheze.org/wiki/Development').style(Style.SuccessHeader).println(' for details.)'
    )
    versionOverride = 'NO-GIT-TAG-SET'
    identifiedVersion = versionOverride
    explicitVersion = false
}
version = minecraftVersion + '-' + identifiedVersion
ext {
    modVersion = identifiedVersion
}

if (identifiedVersion == versionOverride) {
    out.style(Style.Failure).text('Override version to ').style(Style.Identifier).text(modVersion).style(Style.Failure).println('!\7')
}

group = modGroup
archivesBaseName = modId

minecraft {
    version = minecraftVersion + '-' + forgeVersion + '-' + minecraftVersion
    runDir = 'run'

    if (replaceGradleTokenInFile) {
        for (f in replaceGradleTokenInFile.split(',')) {
            replaceIn f
        }
        if (gradleTokenModId) {
            replace gradleTokenModId, modId
        }
        if (gradleTokenModName) {
            replace gradleTokenModName, modName
        }
        if (gradleTokenVersion) {
            replace gradleTokenVersion, modVersion
        }
        if (gradleTokenGroupName) {
            replace gradleTokenGroupName, modGroup
        }
    }

    clientIntellijRun {
        if (developmentEnvironmentUserName) {
            args("--username", developmentEnvironmentUserName)
        }
    }

    serverIntellijRun {}
}

apply from: 'dependencies.gradle'

sourceSets {
    devmode {
        compileClasspath += sourceSets.main.compileClasspath
        compileClasspath += sourceSets.main.output
        java { setSrcDirs(['src/dev/java']) }
        resources { setSrcDirs(['src/dev/resources']) }
    }
}

sourceSets.devmode.resources.matching {
    include 'META-INF/*_at.cfg'
}.each { at->
    logger.lifecycle("Found AccessTransformer in devmode resources: ${at.name}")
    tasks.deobfBinJar.addTransformer(at)
    tasks.deobfuscateJar.addTransformer(at)
}

task generateAssets {}

jar {
    manifest {
        attributes(getManifestAttributes())
    }
}

reobf {}

tasks.jar.finalizedBy('reobf')

tasks.withType(AbstractArchiveTask) {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

afterEvaluate {}

runClient {
    if (developmentEnvironmentUserName) {
        args("--username", developmentEnvironmentUserName)
    }
}

runServer {}

task runClientDev {
    dependsOn 'devmodeJar'
    doFirst {
        tasks.named('runClient').configure {
            dependsOn -= tasks.jar
            classpath = classpath.filter { it != tasks.jar.archivePath }
            classpath file(tasks.devmodeJar.archivePath)
        }
    }
    finalizedBy 'runClient'
}

task runServerDev {
    dependsOn 'devmodeJar'
    doFirst {
        tasks.named('runServer').configure {
            dependsOn -= tasks.jar
            classpath = classpath.filter { it != tasks.jar.archivePath }
            classpath file(tasks.devmodeJar.archivePath)
        }
    }
    finalizedBy 'runServer'
}

tasks.withType(JavaExec).configureEach {
    javaLauncher.set(
        javaToolchains.launcherFor {
            languageVersion = projectJavaVersion
        }
    )
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand "minecraftVersion": project.minecraft.version,
            "modVersion": modVersion,
            "modId": modId,
            "modName": modName
    }

    from(sourceSets.main.resources.srcDirs) {
        include 'assets/' + modId + '/lang/*.json'

        eachFile { fileInfo ->
            def outDir = fileInfo.relativePath.parent.getFile(destinationDir)
            convertJsonLangFile(file, outDir)
        }
    }

    if (explicitVersion) {
        from(sourceSets.main.resources.srcDirs) {
            include 'assets/' + modId + '/protocol_versions.json'

            eachFile { fileInfo->
                def versionsMap = new groovy.json.JsonSlurper().parse(file)
                if (!versionsMap.containsKey(modVersion)) {
                    throw new GradleException("Can't find \"${modVersion}\" in ${fileInfo.name} file")
                }
            }
        }
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'assets/' + modId + '/lang/*.json'
        exclude 'mcmod.info'
    }

    doLast {
        fileTree(dir: destinationDir, include: 'assets/' + modId + '/lang/*.json').each { file ->
            file.delete()
        }
    }
}

task combineDevmodeResourceSources(type: Copy) {
    destinationDir = new File(project.buildDir, "combinedResources/devmode")
    doFirst {
        delete destinationDir
    }
    from(sourceSets.devmode.resources.srcDirs) {
        include 'assets/' + modId + '/lang/*.json'

        eachFile { fileInfo ->
            def outDir = fileInfo.relativePath.parent.getFile(destinationDir)
            def mainFile = sourceSets.main.resources.find{file->file.path.endsWith(fileInfo.sourcePath)}
            if (mainFile != null) {
                def outJsonFile = new File(destinationDir, fileInfo.path)
                outJsonFile.getParentFile().mkdirs()
                combineJsonLangFiles(mainFile, file, outJsonFile)
                fileInfo.exclude()
            }
        }
    }
    from(sourceSets.devmode.resources.srcDirs) {
        include 'META-INF/*_at.cfg'

        eachFile { fileInfo ->
            def mainFile = sourceSets.main.resources.find{file->file.path.endsWith(fileInfo.sourcePath)}
            if (mainFile != null) {
                def outJsonFile = new File(destinationDir, fileInfo.path)
                outJsonFile.getParentFile().mkdirs()
                outJsonFile.text = mainFile.text + '\n' + file.text
                fileInfo.exclude()
            }
        }
    }
    from(sourceSets.main.resources.srcDirs) {
        include 'assets/' + modId + '/lang/*.json'
        include 'META-INF/*_at.cfg'
        eachFile { fileInfo -> fileInfo.exclude() }
    }
}

processDevmodeResources {
    dependsOn 'processResources'
    dependsOn 'combineDevmodeResourceSources'

    from(tasks.combineDevmodeResourceSources.destinationDir) {
        include 'assets/' + modId + '/lang/*.json'

        eachFile { fileInfo ->
            def outDir = fileInfo.relativePath.parent.getFile(destinationDir)
            convertJsonLangFile(file, outDir)
        }
    }

    from(tasks.combineDevmodeResourceSources.destinationDir) {
        include 'META-INF/*_at.cfg'
    }

    doLast {
        fileTree(dir: destinationDir, include: 'assets/' + modId + '/lang/*.json').each { file ->
            file.delete()
        }
    }
}

def getManifestAttributes() {
    def manifestAttributes = [:]
    if (accessTransformersFile) {
        manifestAttributes += ["FMLAT": accessTransformersFile.toString()]
    }
    if (coreModClass) {
        manifestAttributes += ["FMLCorePluginContainsFMLMod": true]
        manifestAttributes += ["FMLCorePlugin": modGroup + "." + coreModClass]
    }
    return manifestAttributes
}

task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
    dependsOn 'processResources'
    from(sourceSets.main.output) {
        include 'assets/' + modId + '/lang/*.lang'
    }
    from file("$projectDir/LICENSE")
}

task deobfJar(type: Jar) {
    classifier = 'deobf'
    dependsOn 'processResources'
    from sourceSets.main.output
    manifest {
        attributes(getManifestAttributes())
    }
}

task apiJar(type: Jar) {
    classifier = 'api'
    from(sourceSets.main.allSource) {
        include modGroupPath + "/" + apiPackagePath + '/**'
    }
    from(sourceSets.main.output) {
        include modGroupPath + "/" + apiPackagePath + '/**'
    }
    from file("$projectDir/LICENSE")
}

task devmodeDeobfJar(type: Jar) {
    classifier = 'devmode-deobf'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {}
    dependsOn 'processResources'
    from(sourceSets.main.output) {}
    manifest {
        attributes(getManifestAttributes())
    }
}

task devmodeJar(type: Jar) {
    classifier = 'devmode'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {}
    dependsOn 'processResources'
    from(sourceSets.main.output) {}
    manifest {
        attributes(getManifestAttributes())
    }
    finalizedBy 'devmodeReobf'
}

task devmodeReobf(type: ReobfTask) {
    doFirst {
        if (minecraft.isDecomp()) {
            deobfFile = tasks.deobfuscateJar.delayedOutput
        }
    }
    dependsOn 'genSrgs'
    dependsOn 'devmodeDeobfJar'
    recompFile = delayedFile(tasks.devmodeJar.archivePath)
    exceptorCfg = delayedFile(tasks.reobf.exceptorCfg)
    srg = delayedFile(tasks.reobf.srg)
    extraSrg = tasks.reobf.extraSrg
    fieldCsv = delayedFile(tasks.reobf.fieldCsv)
    mcVersion = delayedString(tasks.reobf.mcVersion)
    mustRunAfter = [tasks.reobf.mustRunAfter]
    reobf(tasks.devmodeJar, {spec->spec.classpath = sourceSets.devmode.compileClasspath})
}

task devmodeSourcesJar(type: Jar) {
    classifier = 'devmode-sources'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn 'combineDevmodeResourceSources'
    from(tasks.combineDevmodeResourceSources.destinationDir) {}
    from(sourceSets.devmode.allSource) {}
    from(sourceSets.main.allSource) {}
    dependsOn 'processDevmodeResources'
    from(sourceSets.devmode.output) {
        include 'assets/' + modId + '/lang/*.lang'
    }
    dependsOn 'processResources'
    from(sourceSets.main.output) {
        include 'assets/' + modId + '/lang/*.lang'
    }
    from file("$projectDir/LICENSE")
}

artifacts {
    archives sourcesJar
    archives deobfJar
    if (apiPackage) {
        archives apiJar
    }
    archives devmodeJar
    archives devmodeDeobfJar
    archives devmodeSourcesJar
}

tasks.withType(GenerateModuleMetadata) {
    enabled = false
}

// Helper methods

def delayedFile(File file) { return new DelayedFile(file) }
def delayedString(String str) { return new DelayedString(project, str) }

def convertJsonLangFile(File jsonFile, File outDir) {
    def matcher = jsonFile.name =~ /^([a-zA-Z0-9]+)_([a-zA-Z0-9]+).json$/
    matcher.find()
    def language = matcher.group(1)
    def region = matcher.group(2)
    def fileName = language + '_' + region.toUpperCase() + '.lang'
    def langFile = new File(outDir, fileName)
    def translation = new groovy.json.JsonSlurper().parse(jsonFile)
    langFile.withWriter { wr ->
        translation.each { e ->
            wr.println e.key + '=' + e.value
        }
    }
}

def combineJsonLangFiles(File firstFile, File secondFile, File outFile) {
    outFile.text = (
        firstFile.text.replaceAll('\\s*}$', ',') +
        secondFile.text.replaceAll('^\\{', '')
    ).replaceAll(',(\\s*)}$', '$1}')
}

def checkPropertyExists(String propertyName) {
    if (!project.hasProperty(propertyName)) {
        throw new GradleException("This project requires a property \"" + propertyName + "\"! Please add it your \"gradle.properties\".")
    }
}

def propertyDefaultIfUnset(String propertyName, defaultValue) {
    if (!project.hasProperty(propertyName) || project.property(propertyName) == "") {
        project.ext.setProperty(propertyName, defaultValue)
    }
}

def getFile(String relativePath) {
    return new File(projectDir, relativePath)
}
