
repositories {
    maven {
        name 'cc-tweaked'
        url 'https://squiddev.cc/maven/'
    }
    maven {
        name 'jei'
        url 'https://dvs1.progwml6.com/files/maven/'
    }
}

dependencies {
    // cc-tweaked-1.15.2-1.97.1.jar 05314ae5b3a3b1a377761886742b7b91
    compileOnly fg.deobf("org.squiddev:cc-tweaked-${minecraft_version}:${cc_tweaked_version}")
    runtimeOnly fg.deobf("org.squiddev:cc-tweaked-${minecraft_version}:${cc_tweaked_version}")
    // jei-1.15.2-6.0.3.16.jar 99d2b8592713c369fe4b7311755356b7
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}:${jei_version}")
}
