
repositories {
    maven {
        name 'chickenbones'
        url 'https://chickenbones.net/maven/'
    }
}

dependencies {
    // CodeChickenLib-1.7.10-1.1.3.141-dev.jar 0217fdc23e8ef7916a4cf88012ad8a68
    compileOnly "codechicken:CodeChickenLib:1.7.10-1.1.3.141:dev"
    runtime "codechicken:CodeChickenLib:1.7.10-1.1.3.141:dev"
    // CodeChickenCore-1.7.10-1.0.7.48-dev.jar 7b130c10f70c79b4bd79d63ece99e6dc
    compileOnly "codechicken:CodeChickenCore:1.7.10-1.0.7.48:dev"
    runtime "codechicken:CodeChickenCore:1.7.10-1.0.7.48:dev"
    // NotEnoughItems-1.7.10-1.0.5.120-dev.jar df45d2e6357b06abedb68e77e133f07f
    compileOnly "codechicken:NotEnoughItems:1.7.10-1.0.5.120:dev"
    runtime "codechicken:NotEnoughItems:1.7.10-1.0.5.120:dev"
    // ComputerCraft1.75.jar 3d4ab469b955a3def59e260da660927c
    compileOnly "dan200:ComputerCraft:1.75"
    runtime "dan200:ComputerCraft:1.75"
}

task downloadJars {
    doFirst {
        def localrepo = "${gradle.getGradleUserHomeDir()}/caches/minecraft"
        downloadDependencyJar(
            "dan200:ComputerCraft:1.75", localrepo,
            "https://mediafilez.forgecdn.net/files/2269/339/ComputerCraft1.75.jar",
            "3d4ab469b955a3def59e260da660927c"
        )
        repositories {
            maven {
                name 'local-repo'
                url uri(localrepo)
            }
        }
    }
}

tasks.compileJava.dependsOn downloadJars
tasks.eclipse.dependsOn downloadJars
tasks.idea.dependsOn downloadJars

// Methods

def downloadDependencyJar(String dependency, String localrepo, String link, String md5sum) {
    def depparts = dependency.split(':')
    def group = depparts[0]
    def name = depparts[1]
    def version = depparts[2]
    def postfix = depparts.size() > 3 ? '-' + depparts[3] : ''

    def jarpath = "${group}/${name}/${version}/${name}-${version}${postfix}.jar"
    def pompath = "${group}/${name}/${version}/${name}-${version}.pom"
    def jarfile = new File("${localrepo}/${jarpath}")
    def pomfile = new File("${localrepo}/${pompath}")

    if (jarfile.exists() && pomfile.exists()) {
        return
    }

    def detached = configurations.detachedConfiguration(
        dependencies.create(dependency)
    )
    detached.setTransitive(false)

    try {
        def files = detached.resolve()
        if (!files.empty) {
            return
        }
    } catch (Exception e) {
    }

    download.run {
        src link
        dest "${localrepo}/${jarpath}"
        overwrite false
    }

    verifyChecksum.run {
        src "${localrepo}/${jarpath}"
        algorithm 'MD5'
        checksum md5sum
    }

    pomfile.text = """
        <project xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                                     http://maven.apache.org/xsd/maven-4.0.0.xsd">
          <modelVersion>4.0.0</modelVersion>
          <groupId>${group}</groupId>
          <artifactId>${name}</artifactId>
          <name>${name}</name>
          <version>${version}</version>
          <packaging>jar</packaging>
        </project>
    """.stripIndent().trim() + "\n"
}
