
repositories {
    maven {
        name 'cc-tweaked'
        url 'https://squiddev.cc/maven/'
    }
    maven {
        name 'jei'
        url 'https://dvs1.progwml6.com/files/maven/'
    }
}

dependencies {
    // cc-tweaked-1.16.5-1.101.3.jar 537a921345bc5bf41bc0ac639570df70
    compileOnly fg.deobf("org.squiddev:cc-tweaked-${minecraft_version}:${cc_tweaked_version}")
    runtimeOnly fg.deobf("org.squiddev:cc-tweaked-${minecraft_version}:${cc_tweaked_version}")
    // jei-1.16.5-7.7.1.153.jar c632d0ad38292ad77d1624aa6c97fdac
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}:${jei_version}")
}
