mod_name = PanicleCraft
mod_id = paniclecraft
mod_group = com.vanym.paniclecraft

minecraft_version=1.16.5
minecraft_version_range=[1.16,1.17)
forge_version=36.2.42
forge_version_range=[36,)

mcp_mappings_channel=parchment
mcp_mappings_version=2022.03.06-1.16.5

cc_tweaked_version=1.101.3
jei_version=7.7.1.153

development_environment_username = Developer

api_package = api

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
