modName = PanicleCraft
modId = paniclecraft
modGroup = com.vanym.paniclecraft

minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

codechickenlibVersion = 1.1.3.141
codechickencoreVersion = 1.0.7.48
notenoughitemsVersion = 1.0.5.120
computercraftVersion = 1.75

developmentEnvironmentUserName = Developer

replaceGradleTokenInFile = DEF.java
gradleTokenModId = GRADLETOKEN_MODID
gradleTokenModName = GRADLETOKEN_MODNAME
gradleTokenVersion = GRADLETOKEN_VERSION
gradleTokenGroupName = GRADLETOKEN_GROUPNAME

apiPackage = api

accessTransformersFile = paniclecraft_at.cfg
