package ee_man.mod3;

import java.util.Arrays;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import ee_man.mod3.core.GuiHandler;
import ee_man.mod3.init.ModItems;
import ee_man.mod3.network.PacketHandler;
import ee_man.mod3.proxy.IProxy;

@Mod(modid = DEF.MOD_ID, name = DEF.MOD_NAME, version = DEF.VERSION)
public class Core{
	
	@Instance(DEF.MOD_ID)
	public static Core instance;
	
	@SidedProxy(clientSide = "ee_man.mod3.proxy.ClientProxy", serverSide = "ee_man.mod3.proxy.ServerProxy", modId = DEF.MOD_ID)
	public static IProxy proxy;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event){
		ModMetadata modMeta = event.getModMetadata();
		modMeta.modId = DEF.MOD_ID;
		modMeta.name = DEF.MOD_NAME;
		modMeta.authorList = Arrays.asList(new String[]{"ee_man"});
		modMeta.url = "http://www.minecraftforum.net/topic/1715756-";
		modMeta.description = "Create, Play or Draw and Clean up After";
		modMeta.version = DEF.VERSION;
		modMeta.autogenerated = false;
		Config.init(event.getSuggestedConfigurationFile());
		ModItems.init(Config.getConfig());
		PacketHandler.init();
		proxy.preInit(Config.getConfig());
		if(Loader.isModLoaded("ComputerCraft")){
			ee_man.mod3.plugins.computercraft.ComputerCraftPlugin.init(Config.getConfig());
		}
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event){
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, new GuiHandler());
		proxy.init(Config.getConfig());
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event){
		proxy.postInit(Config.getConfig());
		Config.save();
	}
}
